[package]
name = "stateful"
version = "0.1.0"
edition = "2018"
license = "MIT"
description = "Hierarchial state machine with function pointers"
readme = "README.md"
keywords = ["hierarchial state machine"]


[dependencies]
heapless = "0.7.7"
stateful_derive = { path = "stateful_derive" }

[features]
