[workspace]
members = [
    # Core stateful crates
    "stateful",

    # Examples
    "examples/basic",
    "examples/blinky",
    "examples/history",
    "examples/bench",
    "examples/calculator",
]
